# Generated by Django 2.2 on 2019-11-16 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[('excellent', '5'), ('good', '4'), ('so-so', '3'), ('bad', '2'), ('awfully', '1')], verbose_name='Оценка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_review', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_review', to='webapp.Services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
